sudo: required
language: bash

install:
  - sudo apt-get install -y vagrant
  - sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install virtualbox-4.2
  - VBoxManage -v

script:
  - vagrant box add bitroid https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box
  - sudo vagrant up
  - sudo vagrant ssh -c 'wget -O- localhost'
  - exit

after_script:
  - vagrant destroy

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
