sudo: required
language: bash

install:
  - sudo apt-get install -y vagrant
  - sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install virtualbox-4.2
  - VBoxManage -v

script:
  - vagrant up
  - vagrant ssh
  - wget -O- localhost:8080
  - exit

after_script:
  - vagrant destroy
